#!/usr/bin/env bash
set -euo pipefail

# Generated by monedula-acl-rbac emit --format script
# Plan: <RUNDIR>/plan.json
# Bindings: 1 to create, 1 to skip (already exist).

confluent iam rbac role-binding create \
  --principal 'User:alice' \
  --role 'DeveloperRead' \
  --kafka-cluster 'lkc-kafka01' \
  --resource 'Topic:orders'  # binding rb-aaaaaaaaaaaa (source_acl_ids=[1 2])
# SKIP (already exists in MDS): DeveloperWrite for User:bob on Topic:events.
