#!/usr/bin/env bash
set -euo pipefail

# Generated by monedula-acl-rbac <VERSION>
# Generated at: <TIMESTAMP>
# plan.sha256 = f491c57fb1df655249a459e56aaaf118146ef1946a847dc14b84d10ccebeda77
# verify.sha256 = 573c13e714c7a5f393d20aa65a555966d05f09d22842c4653ffc2bebeab8fd85
# bootstrap-server: kafka.example.com:9093
# Principals (1):
#   User:alice
# Run directory (absolute): <RUNDIR>

# Refuse to run if plan.json was edited after script generation.
# Set MONEDULA_SKIP_PLAN_HASH_CHECK=1 to skip when plan.json is intentionally
# not co-located with the script at run time (e.g. inside a broker container).
EXPECTED_PLAN_SHA256='f491c57fb1df655249a459e56aaaf118146ef1946a847dc14b84d10ccebeda77'
if [ "${MONEDULA_SKIP_PLAN_HASH_CHECK:-}" = "1" ]; then
  echo "delete script: MONEDULA_SKIP_PLAN_HASH_CHECK=1 set; skipping plan.json integrity check" >&2
else
  ACTUAL_PLAN_SHA256=<SHA256SUM-OF-RUNDIR-PLAN>
  if [ -z "$ACTUAL_PLAN_SHA256" ]; then
    echo "delete script: cannot hash plan.json (no sha256sum/shasum, or file not readable here) — refusing to run. Set MONEDULA_SKIP_PLAN_HASH_CHECK=1 to override." >&2
    exit 5
  elif [ "$EXPECTED_PLAN_SHA256" != "$ACTUAL_PLAN_SHA256" ]; then
    echo "delete script: plan.json hash mismatch — refusing to run. Re-generate with delete-acls / delete-deny-acls." >&2
    exit 5
  fi
fi

LOG=<RUNDIR>/delete.log

ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }
log() { printf '%s\t%s\n' "$(ts)" "$1" >> "$LOG"; }

trap 'log SUMMARY exit=$?' EXIT

if kafka-acls '--bootstrap-server' 'kafka.example.com:9093' '--remove' '--force' '--allow-principal' 'User:alice' '--operation' 'Read' '--resource-pattern-type' 'literal' '--topic' 'orders'; then log 'OK acl_id=1'; else log 'FAIL acl_id=1'; exit 1; fi
if kafka-acls '--bootstrap-server' 'kafka.example.com:9093' '--remove' '--force' '--allow-principal' 'User:alice' '--operation' 'Describe' '--resource-pattern-type' 'literal' '--topic' 'orders'; then log 'OK acl_id=2'; else log 'FAIL acl_id=2'; exit 1; fi
