#!/usr/bin/env bash
set -euo pipefail

# Generated by monedula-acl-rbac emit --format script
# Plan: out/plan.json
# Bindings: 7 to create, 0 to skip (already exist).

confluent iam rbac role-binding create \
  --principal 'User:svc-payments-producer' \
  --role 'DeveloperWrite' \
  --kafka-cluster 'lkc-demo-1' \
  --resource 'Topic:payments'  # binding rb-3713a985833c (source_acl_ids=[12 13])
confluent iam rbac role-binding create \
  --principal 'User:svc-orders-owner' \
  --role 'ResourceOwner' \
  --kafka-cluster 'lkc-demo-1' \
  --resource 'Topic:orders'  # binding rb-487eba1f8a6d (source_acl_ids=[8])
confluent iam rbac role-binding create \
  --principal 'User:svc-orders-consumer' \
  --role 'DeveloperRead' \
  --kafka-cluster 'lkc-demo-1' \
  --resource 'Group:orders-consumers'  # binding rb-80316b05c1c2 (source_acl_ids=[6 7])
confluent iam rbac role-binding create \
  --principal 'User:svc-orders-relay' \
  --role 'DeveloperWrite' \
  --kafka-cluster 'lkc-demo-1' \
  --resource 'Topic:orders'  # binding rb-835674b14104 (source_acl_ids=[9 10 11])
confluent iam rbac role-binding create \
  --principal 'User:svc-orders-relay' \
  --role 'DeveloperRead' \
  --kafka-cluster 'lkc-demo-1' \
  --resource 'Topic:orders'  # binding rb-9f2d509a84c4 (source_acl_ids=[9 10 11])
confluent iam rbac role-binding create \
  --principal 'User:svc-orders-consumer' \
  --role 'DeveloperRead' \
  --kafka-cluster 'lkc-demo-1' \
  --resource 'Topic:orders'  # binding rb-b3154d837238 (source_acl_ids=[4 5])
confluent iam rbac role-binding create \
  --principal 'User:svc-analytics' \
  --role 'DeveloperRead' \
  --kafka-cluster 'lkc-demo-1' \
  --resource 'Topic:events.' --prefix  # binding rb-b6fac2ae9aa0 (source_acl_ids=[2 3])
