#!/usr/bin/env bash
set -euo pipefail

# Generated by monedula-acl-rbac emit --format mds-curl
# Plan: <RUNDIR>/plan.json
# Bindings: 1 to create, 1 to skip (already exist).
#
# Required environment variables:
#   MDS_URL          MDS base URL (e.g., https://mds.example.com)
#   MDS_TOKEN        Bearer token (see monedula-acl-rbac auth login)

: "${MDS_URL:?MDS_URL is required}"
: "${MDS_TOKEN:?MDS_TOKEN is required}"

# binding rb-aaaaaaaaaaaa (source_acl_ids=[1 2])
curl -fsS -X POST \
  -H "Authorization: Bearer ${MDS_TOKEN}" \
  -H 'Content-Type: application/json' \
  -d '{"scope":{"clusters":{"kafka-cluster":"lkc-kafka01"}},"resourcePatterns":[{"resourceType":"Topic","name":"orders","patternType":"LITERAL"}]}' \
  "${MDS_URL}/security/1.0/principals/User:alice/roles/DeveloperRead/bindings"
# SKIP (already exists in MDS): binding rb-bbbbbbbbbbbb
