// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 Monedula contributors

package acls_test

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/monedula-dev/monedula-acl-rbac-converter/pkg/aclrbac/delete/acls"
	"github.com/monedula-dev/monedula-acl-rbac-converter/pkg/aclrbac/rundir"
	"github.com/monedula-dev/monedula-acl-rbac-converter/pkg/aclrbac/types"
	"github.com/monedula-dev/monedula-acl-rbac-converter/pkg/aclrbac/verify"
)

var updateGolden = flag.Bool("update", false, "rewrite golden delete-acls.sh from the current output")

// reDateLine replaces the "# Generated at: <rfc3339>" line with a stable
// placeholder so that golden comparisons are not broken by wall-clock skew.
var reDateLine = regexp.MustCompile(`(?m)^# Generated at: .+$`)

// reRunDir replaces run-dir and LOG= lines that embed the temp directory, which
// varies per machine and per test run.
var reRunDir = regexp.MustCompile(`(?m)^# Run directory \(absolute\): .+$`)
var reLogLine = regexp.MustCompile(`(?m)^LOG=.+$`)

// reActualSHA masks the runtime plan.sha256 guard's sha256sum invocation,
// which embeds the per-run temp directory in the plan.json path. The line is
// indented (it lives inside the fail-closed `else` block), so the leading
// whitespace is captured and preserved while the path-bearing tail is masked —
// without the `\s*` the anchored match would miss the indented line and leak
// the absolute temp path (incl. a developer username) into the committed golden.
var reActualSHA = regexp.MustCompile(`(?m)^(\s*)ACTUAL_PLAN_SHA256=.+$`)

// reVersionLine masks the tool-version line. version.Version is "dev" in
// raw `go test`, a release tag under goreleaser, and a vcs hash under
// `go install ...@vX.Y.Z`. The script must contain *something* here, but
// the exact value is environment-dependent.
var reVersionLine = regexp.MustCompile(`(?m)^# Generated by monedula-acl-rbac .+$`)

func normalizeScript(b []byte) []byte {
	b = reDateLine.ReplaceAll(b, []byte("# Generated at: <TIMESTAMP>"))
	b = reRunDir.ReplaceAll(b, []byte("# Run directory (absolute): <RUNDIR>"))
	b = reLogLine.ReplaceAll(b, []byte("LOG=<RUNDIR>/delete.log"))
	b = reActualSHA.ReplaceAll(b, []byte("${1}ACTUAL_PLAN_SHA256=<SHA256SUM-OF-RUNDIR-PLAN>"))
	b = reVersionLine.ReplaceAll(b, []byte("# Generated by monedula-acl-rbac <VERSION>"))
	return b
}

func sampleVerifyOK() []verify.Result {
	return []verify.Result{
		{BindingID: "rb-aaaaaaaaaaaa", Status: verify.StatusEffectiveOK},
	}
}

func sampleACLSet() types.ACLSet {
	return types.ACLSet{
		SchemaVersion: "1",
		Source:        types.ACLSetSource{Type: "json", GeneratedAt: "2026-05-24T00:00:00Z"},
		ACLs: []types.ACLRow{
			{ID: 1, Principal: "User:alice", Host: "*", Operation: types.OpRead, ResourceType: types.ResourceTopic, ResourceName: "orders", PatternType: types.PatternLiteral, PermissionType: types.PermissionAllow},
			{ID: 2, Principal: "User:alice", Host: "*", Operation: types.OpDescribe, ResourceType: types.ResourceTopic, ResourceName: "orders", PatternType: types.PatternLiteral, PermissionType: types.PermissionAllow},
		},
	}
}

func TestGoldenDeleteACLsScript(t *testing.T) {
	dir := t.TempDir()
	planPath := filepath.Join(dir, "plan.json")

	plan := samplePlan()
	if err := rundir.WritePlan(planPath, plan); err != nil {
		t.Fatalf("write plan: %v", err)
	}
	if err := rundir.WriteChecksum(planPath); err != nil {
		t.Fatalf("write checksum: %v", err)
	}

	aclSet := sampleACLSet()
	aclsPath := filepath.Join(dir, "acls.json")
	if err := rundir.WriteACLs(aclsPath, aclSet); err != nil {
		t.Fatalf("write acls: %v", err)
	}

	// Write verify.json so the script header gets a stable verify.sha256.
	// We hand-marshal a fixed-bytes envelope (skipping verify.WriteSummary)
	// so the SHA-256 is deterministic across machines and Go versions.
	verifyPath := filepath.Join(dir, "verify.json")
	verifyBody := []byte(`{"results":[{"binding_id":"rb-aaaaaaaaaaaa","status":"EFFECTIVE_OK"}]}`)
	if err := os.WriteFile(verifyPath, verifyBody, 0o600); err != nil {
		t.Fatalf("write verify.json: %v", err)
	}
	// Parse it back into Result slice so Generate's eligibility check
	// sees the same data the script header SHA-256s.
	var probe struct {
		Results []verify.Result `json:"results"`
	}
	if err := json.Unmarshal(verifyBody, &probe); err != nil {
		t.Fatalf("decode verify fixture: %v", err)
	}

	err := acls.Generate(acls.Options{
		RunDir:           dir,
		PlanPath:         planPath,
		VerifyPath:       verifyPath,
		ACLsPath:         aclsPath,
		Verify:           probe.Results,
		Principals:       []string{"User:alice"},
		BootstrapServers: "kafka.example.com:9093",
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	got, err := os.ReadFile(filepath.Join(dir, "delete-acls.sh"))
	if err != nil {
		t.Fatalf("read generated delete-acls.sh: %v", err)
	}

	goldenPath := filepath.Join("testdata", "golden", "delete-acls.sh")

	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		// Persist the NORMALIZED form, never the raw output. The raw script
		// embeds the per-run temp directory (an absolute path that, on a
		// developer's machine, includes their username) into the run-dir,
		// LOG=, and ACTUAL_PLAN_SHA256 lines. Writing the raw output would
		// bake that machine-specific path into a committed file — and the
		// comparison below normalizes both sides anyway, so a raw golden buys
		// nothing. The verbatim parts of the script (shebang, strict mode,
		// SHA-256 header, hash-guard, kafka-acls lines) survive normalization
		// untouched and remain readable.
		if err := os.WriteFile(goldenPath, normalizeScript(got), 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("updated %s (normalized)", goldenPath)
		return
	}

	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden %s: %v (run with -update to seed it)", goldenPath, err)
	}

	if !bytes.Equal(normalizeScript(want), normalizeScript(got)) {
		t.Errorf("golden mismatch.\nwant (normalized):\n%s\n\ngot (normalized):\n%s\n\nRerun with -update if the change is intentional.",
			normalizeScript(want), normalizeScript(got))
	}

	// Spec safety requirements — assert on the raw (un-normalized) output.
	t.Run("shebang", func(t *testing.T) {
		if !strings.HasPrefix(string(got), "#!/usr/bin/env bash\n") {
			t.Errorf("first line must be #!/usr/bin/env bash; got:\n%s", firstLines(got, 2))
		}
	})
	t.Run("strict_mode", func(t *testing.T) {
		lines := strings.SplitN(string(got), "\n", 3)
		if len(lines) < 2 || lines[1] != "set -euo pipefail" {
			t.Errorf("second line must be 'set -euo pipefail'; got:\n%s", firstLines(got, 3))
		}
	})
	t.Run("timestamp_present", func(t *testing.T) {
		if !reDateLine.Match(got) {
			t.Errorf("script does not contain a '# Generated at:' timestamp line")
		}
	})
	t.Run("sha256_present", func(t *testing.T) {
		// Spec §4.3 generated-script safety contract requires plan.json
		// and verify.json SHA-256 in the header so operators auditing the
		// script later can confirm which inputs it was generated from.
		// Asserting on the literal hex avoids a regression where the
		// values revert to empty strings.
		for _, want := range []string{
			"# plan.sha256 = f491c57fb1df655249a459e56aaaf118146ef1946a847dc14b84d10ccebeda77",
			"# verify.sha256 = 573c13e714c7a5f393d20aa65a555966d05f09d22842c4653ffc2bebeab8fd85",
		} {
			if !strings.Contains(string(got), want) {
				t.Errorf("script header missing fingerprint line %q", want)
			}
		}
	})
	t.Run("kafka_acls_remove", func(t *testing.T) {
		// Every argv element except the binary is shell.Quote'd — including
		// flag names — so a value starting with "--" can't escape quoting
		// (see the fix in writeRemove and the regression test below).
		for _, want := range []string{
			"kafka-acls",
			"'--remove'",
			"'--allow-principal' 'User:alice'",
			"'--topic' 'orders'",
		} {
			if !strings.Contains(string(got), want) {
				t.Errorf("script missing %q", want)
			}
		}
	})
	t.Run("dash_dash_value_is_quoted", func(t *testing.T) {
		// Regression guard (security): an operator-supplied value that happens
		// to start with "--" must still be single-quoted in the emitted line.
		// A previous revision exempted any arg starting with "--" from quoting
		// — fine for the literal flag NAMES, but it also matched VALUES, so a
		// crafted topic name like `--$(curl evil)` produced bash command
		// substitution at script-run time. shell metas like `$`/`(`/`)` are
		// not control characters so they pass schema/value validation, which
		// is precisely why this gate matters.
		d := t.TempDir()
		pp := filepath.Join(d, "plan.json")
		if err := rundir.WritePlan(pp, samplePlan()); err != nil {
			t.Fatal(err)
		}
		if err := rundir.WriteChecksum(pp); err != nil {
			t.Fatal(err)
		}
		set := sampleACLSet()
		set.ACLs[0].ResourceName = "--$(curl evil)"
		ap := filepath.Join(d, "acls.json")
		if err := rundir.WriteACLs(ap, set); err != nil {
			t.Fatal(err)
		}
		vp := filepath.Join(d, "verify.json")
		if err := os.WriteFile(vp, []byte(`{"results":[{"binding_id":"rb-aaaaaaaaaaaa","status":"EFFECTIVE_OK"}]}`), 0o600); err != nil {
			t.Fatal(err)
		}
		if err := acls.Generate(acls.Options{
			RunDir: d, PlanPath: pp, VerifyPath: vp, ACLsPath: ap,
			Verify: sampleVerifyOK(), Principals: []string{"User:alice"},
			BootstrapServers: "kafka.example.com:9093",
		}); err != nil {
			t.Fatal(err)
		}
		b, err := os.ReadFile(filepath.Join(d, "delete-acls.sh"))
		if err != nil {
			t.Fatal(err)
		}
		s := string(b)
		if !strings.Contains(s, `'--topic' '--$(curl evil)'`) {
			t.Errorf("a value starting with -- must be single-quoted; emitted:\n%s", s)
		}
		// The bare unquoted form would look like ` --$(curl evil)` (preceded
		// by a space, not inside single quotes). If we ever see that, the
		// quoting fix has regressed.
		if strings.Contains(s, " --$(curl evil) ") || strings.Contains(s, " --$(curl evil);") {
			t.Errorf("found UNQUOTED `--$(curl evil)` in the script — shell-injection vector:\n%s", s)
		}
	})
	t.Run("shell_quoting", func(t *testing.T) {
		// Principal and topic must use single-quote shell quoting.
		if !strings.Contains(string(got), "'User:alice'") {
			t.Errorf("principal not single-quoted in script")
		}
		if !strings.Contains(string(got), "'orders'") {
			t.Errorf("topic not single-quoted in script")
		}
	})
	t.Run("absolute_run_dir", func(t *testing.T) {
		// The script header emits the run directory as an absolute path.
		if !strings.Contains(string(got), "# Run directory (absolute):") {
			t.Errorf("script missing absolute run-directory comment")
		}
	})
}

func firstLines(b []byte, n int) string {
	lines := strings.SplitN(string(b), "\n", n+1)
	if len(lines) > n {
		lines = lines[:n]
	}
	return strings.Join(lines, "\n")
}
