// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 Monedula contributors

// Package common holds the safety-contract helpers shared by `delete-acls`
// and `delete-deny-acls` script generation.
package common

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/monedula-dev/monedula-acl-rbac-converter/pkg/aclrbac/emit/shell"
)

// FileSHA256 returns the hex-encoded SHA-256 digest of the file at path.
// Empty path returns ("", nil) so callers can pass optional artefacts
// (e.g., verify.json for rollback scripts that don't need it). Read
// errors are returned to the caller — the SHA-256 lines in the script
// header are spec §4.3 safety-contract values, not optional decorations.
func FileSHA256(path string) (string, error) {
	if path == "" {
		return "", nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("sha256 %s: %w", path, err)
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}

// VerifyACLsSHA refuses to proceed when the plan was stamped with an
// acls.json SHA (acls_sha256) that no longer matches the file at aclsPath.
// The destructive delete commands select kafka-acls argv from acls.json by
// row id, so a regenerated or hand-edited acls.json could target a different
// ACL than the plan analyzed. A plan with no stamped SHA (empty) is accepted
// for backward compatibility with plans produced before stamping existed.
func VerifyACLsSHA(planACLsSHA256, aclsPath string) error {
	if planACLsSHA256 == "" {
		return nil
	}
	got, err := FileSHA256(aclsPath)
	if err != nil {
		return err
	}
	if got != planACLsSHA256 {
		return fmt.Errorf("acls.json has changed since planning (sha256 %s != plan's %s); regenerate the plan against the current acls.json before deleting",
			got, planACLsSHA256)
	}
	return nil
}

// HeaderInputs feeds BuildScriptHeader.
type HeaderInputs struct {
	ToolVersion      string
	GeneratedAt      time.Time
	PlanSHA256       string
	VerifySHA256     string
	BootstrapServers string
	CommandConfig    string
	MDSURL           string
	Principals       []string
	RunDir           string // absolute path

	// EarlyExitSetup, if non-empty, is emitted VERBATIM immediately after
	// `set -euo pipefail` and BEFORE the plan.sha256 integrity guard below.
	// Used to arm an EXIT trap (and any supporting shell-variable assignments)
	// early so an early guard exit — hash mismatch, unhashable plan, or a
	// downstream guard like the runtime.env mode check — still runs cleanup.
	//
	// Pass a complete block (e.g. a `VAR=...` assignment followed by the
	// `trap '...' EXIT` line). The header does NOT wrap this in `trap '...'`,
	// so callers can avoid nested single-quoting against shell.Quote'd paths
	// (which splits on spaces in the run directory): assign the path to a
	// shell variable here and reference it inside the trap via `"$VAR"`.
	// delete-acls leaves this empty (no runtime.env to clean up).
	EarlyExitSetup string
}

// BuildScriptHeader returns the shebang + strict-mode + comment header
// shared by delete-acls.sh and delete-deny-acls.sh (spec §4.3
// safety contract).
func BuildScriptHeader(in HeaderInputs) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("set -euo pipefail\n\n")
	// Emit the caller's early-exit setup (typically a `VAR=path` assignment +
	// `trap '...' EXIT`) BEFORE the integrity guard below, so an early exit
	// (plan.json hash mismatch / unhashable / a downstream guard like the
	// runtime.env mode check) still runs cleanup. Without this the trap would
	// only be armed after the guard, leaving sensitive artefacts (the per-run
	// runtime.env auth-token file) behind on an early abort. Emitted verbatim
	// so the caller can reference its assigned variables inside the trap and
	// avoid nested single-quote splitting on space-containing run-dir paths.
	if in.EarlyExitSetup != "" {
		fmt.Fprintf(&b, "%s\n\n", in.EarlyExitSetup)
	}
	// `s` is the operator-controlled fields below (bootstrap server, MDS URL,
	// run-dir path, principal names). Every one of them is written into a
	// `# ...` comment line via `%s`, so a '\n' would escape the comment and
	// be interpreted as bash. types.ValidateACLSet (called from
	// rundir.WriteACLs/ReadACLs) already rejects rows with control chars in
	// Principal/Host/ResourceName, but BootstrapServers / MDSURL / RunDir
	// come from CLI flags / filepath.Abs and don't go through that gate, and
	// future code changes could route raw input here. Sanitise defensively.
	s := sanitiseHeaderField
	fmt.Fprintf(&b, "# Generated by monedula-acl-rbac %s\n", s(nzWithFallback(in.ToolVersion, "(unset)")))
	fmt.Fprintf(&b, "# Generated at: %s\n", in.GeneratedAt.UTC().Format(time.RFC3339))
	if in.PlanSHA256 != "" {
		fmt.Fprintf(&b, "# plan.sha256 = %s\n", s(in.PlanSHA256))
	}
	if in.VerifySHA256 != "" {
		fmt.Fprintf(&b, "# verify.sha256 = %s\n", s(in.VerifySHA256))
	}
	if in.BootstrapServers != "" {
		fmt.Fprintf(&b, "# bootstrap-server: %s\n", s(in.BootstrapServers))
	}
	if in.CommandConfig != "" {
		fmt.Fprintf(&b, "# command-config: %s\n", s(in.CommandConfig))
	}
	if in.MDSURL != "" {
		fmt.Fprintf(&b, "# mds-url: %s\n", s(in.MDSURL))
	}
	if len(in.Principals) > 0 {
		fmt.Fprintf(&b, "# Principals (%d):\n", len(in.Principals))
		for _, p := range in.Principals {
			fmt.Fprintf(&b, "#   %s\n", s(p))
		}
	}
	if in.RunDir != "" {
		fmt.Fprintf(&b, "# Run directory (absolute): %s\n", s(in.RunDir))
	}
	b.WriteString("\n")

	// Runtime plan.sha256 guard: refuse to run if plan.json was edited
	// after this script was generated. The destructive kafka-acls calls
	// below trust the DENY analysis / eligibility decisions baked into the
	// script at generation time; if plan.json changed since then, those
	// decisions no longer describe the plan on disk. Exit 5 (the tool's
	// "integrity/precondition failure" code).
	//
	// The check is FAIL-CLOSED: if plan.json cannot be hashed (no
	// sha256sum/shasum on PATH, or the file isn't readable where the script
	// runs), the script refuses to run (exit 5) rather than proceeding blind.
	// The single documented escape hatch is MONEDULA_SKIP_PLAN_HASH_CHECK=1,
	// for when plan.json is intentionally not co-located with the script at run
	// time (e.g. executing the script inside a broker container that ships
	// kafka-acls but not the run directory). `|| true` only keeps the command
	// substitution from tripping `set -e` BEFORE we test for emptiness — the
	// emptiness test then drives the explicit exit 5, so the refusal does not
	// rely on set -e.
	//
	// The file is fed on STDIN (`sha256sum < path`) rather than as an argument
	// so the tool reports filename "-": GNU coreutils prepends a "\" escape to
	// the checksum line when the filename contains a backslash (a Windows
	// run-dir path under Git Bash/Cygwin), which would corrupt the parsed hash
	// and cause a false "hash mismatch".
	if in.PlanSHA256 != "" && in.RunDir != "" {
		planPath := shell.Quote(filepath.Join(in.RunDir, "plan.json"))
		fmt.Fprintf(&b, "# Refuse to run if plan.json was edited after script generation.\n")
		fmt.Fprintf(&b, "# Set MONEDULA_SKIP_PLAN_HASH_CHECK=1 to skip when plan.json is intentionally\n")
		fmt.Fprintf(&b, "# not co-located with the script at run time (e.g. inside a broker container).\n")
		fmt.Fprintf(&b, "EXPECTED_PLAN_SHA256='%s'\n", in.PlanSHA256)
		b.WriteString("if [ \"${MONEDULA_SKIP_PLAN_HASH_CHECK:-}\" = \"1\" ]; then\n")
		b.WriteString("  echo \"delete script: MONEDULA_SKIP_PLAN_HASH_CHECK=1 set; skipping plan.json integrity check\" >&2\n")
		b.WriteString("else\n")
		fmt.Fprintf(&b, "  ACTUAL_PLAN_SHA256=\"$( { sha256sum < %s 2>/dev/null || shasum -a 256 < %s 2>/dev/null || true; } | awk '{print $1}')\"\n", planPath, planPath)
		b.WriteString("  if [ -z \"$ACTUAL_PLAN_SHA256\" ]; then\n")
		b.WriteString("    echo \"delete script: cannot hash plan.json (no sha256sum/shasum, or file not readable here) — refusing to run. Set MONEDULA_SKIP_PLAN_HASH_CHECK=1 to override.\" >&2\n")
		b.WriteString("    exit 5\n")
		b.WriteString("  elif [ \"$EXPECTED_PLAN_SHA256\" != \"$ACTUAL_PLAN_SHA256\" ]; then\n")
		b.WriteString("    echo \"delete script: plan.json hash mismatch — refusing to run. Re-generate with delete-acls / delete-deny-acls.\" >&2\n")
		b.WriteString("    exit 5\n")
		b.WriteString("  fi\n")
		b.WriteString("fi\n\n")
	}
	return b.String()
}

func nzWithFallback(s, fallback string) string {
	if s == "" {
		return fallback
	}
	return s
}

// sanitiseHeaderField replaces every control character (rune < 0x20 or 0x7f)
// with '?' so the resulting bytes are safe to interpolate into a single-line
// `#` comment in the emitted script. Defence-in-depth: types.ValidateACLSet
// already rejects ACL rows with control chars in Principal/Host/ResourceName
// at WriteACLs/ReadACLs time, but BootstrapServers / MDSURL / RunDir / the
// tool version string don't go through that gate. A '\n' in any of these
// would have escaped the `#` comment and run as bash at script-execution
// time, before any guard or trap fired.
func sanitiseHeaderField(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			b.WriteByte('?')
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}
