// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 Monedula contributors

// Package mdscurl renders a Plan as a runnable bash script of `curl`
// commands against the MDS REST API.
package mdscurl

import (
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"strings"

	"github.com/monedula-dev/monedula-acl-rbac-converter/pkg/aclrbac/emit"
	"github.com/monedula-dev/monedula-acl-rbac-converter/pkg/aclrbac/emit/shell"
	"github.com/monedula-dev/monedula-acl-rbac-converter/pkg/aclrbac/types"
)

type Options struct {
	PlanPath string
}

type Emitter struct {
	opts Options
}

func New(opts Options) *Emitter { return &Emitter{opts: opts} }

func (e *Emitter) Name() string { return "mds-curl" }

func (e *Emitter) Emit(w io.Writer, plan types.Plan) (int, error) {
	created := 0
	skipped := 0
	for _, b := range plan.Bindings {
		if b.Action == types.ActionCreate {
			created++
		}
		if b.Action == types.ActionSkipExists {
			skipped++
		}
	}

	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("set -euo pipefail\n\n")
	b.WriteString("# Generated by monedula-acl-rbac emit --format mds-curl\n")
	if e.opts.PlanPath != "" {
		b.WriteString("# Plan: " + e.opts.PlanPath + "\n")
	}
	fmt.Fprintf(&b, "# Bindings: %d to create, %d to skip (already exist).\n", created, skipped)
	b.WriteString("#\n")
	b.WriteString("# Required environment variables:\n")
	b.WriteString("#   MDS_URL          MDS base URL (e.g., https://mds.example.com)\n")
	b.WriteString("#   MDS_TOKEN        Bearer token (see monedula-acl-rbac auth login)\n\n")
	b.WriteString(": \"${MDS_URL:?MDS_URL is required}\"\n")
	b.WriteString(": \"${MDS_TOKEN:?MDS_TOKEN is required}\"\n\n")

	for _, bd := range emit.OrderedBindings(plan.Bindings) {
		if bd.Action == types.ActionSkipExists {
			fmt.Fprintf(&b, "# SKIP (already exists in MDS): binding %s\n", emit.SanitizeComment(bd.ID))
			continue
		}
		fmt.Fprintf(&b, "# binding %s (source_acl_ids=%v)\n", emit.SanitizeComment(bd.ID), bd.SourceACLIDs)
		if bd.Scope.Organization != "" || bd.Scope.Environment != "" {
			fmt.Fprintf(&b, "# WARNING: binding %s has organization/environment scope which this MDS scope body cannot represent; it is omitted\n",
				emit.SanitizeComment(bd.ID))
		}
		body := buildBody(bd)
		bodyJSON, _ := json.Marshal(body)

		// Principal and Role go into a URL path segment that is itself
		// embedded in a double-quoted shell string (so ${MDS_URL} and
		// ${MDS_TOKEN} expand at script run time). Two distinct attack
		// surfaces, both addressed by escapePathSegment below:
		//   1. URL injection — a principal containing '?', '#', '/'
		//      or whitespace would corrupt the request line. Handled
		//      by net/url.PathEscape.
		//   2. Shell interpolation — url.PathEscape deliberately leaves
		//      '$' and ':' alone (both are valid in a path segment per
		//      RFC 3986), but '$' inside a double-quoted bash string
		//      triggers variable expansion: a principal named
		//      "User:alice$HOME" would have $HOME substituted when the
		//      operator runs the generated script. The same applies to
		//      backticks (command substitution), '"' (closes the
		//      string), and '\' (escape character). escapePathSegment
		//      percent-encodes that quartet on top of PathEscape so the
		//      generated URL is safe inside double quotes too.
		escapedPrincipal := escapePathSegment(bd.Principal)
		escapedRole := escapePathSegment(bd.Role)
		b.WriteString("curl -fsS -X POST \\\n")
		b.WriteString("  -H \"Authorization: Bearer ${MDS_TOKEN}\" \\\n")
		b.WriteString("  -H 'Content-Type: application/json' \\\n")
		fmt.Fprintf(&b, "  -d %s \\\n", shell.Quote(string(bodyJSON)))
		fmt.Fprintf(&b, "  \"${MDS_URL}/security/1.0/principals/%s/roles/%s/bindings\"\n",
			escapedPrincipal, escapedRole)
	}

	_, err := io.WriteString(w, b.String())
	return created, err
}

// The MDS REST API uses camelCase keys (resourcePatterns/resourceType/
// patternType); the scope.clusters keys ("kafka-cluster" etc.) are
// hyphenated. Verified empirically against Confluent MDS — snake_case keys
// are silently ignored and the request rejected with HTTP 400.
type bodyDoc struct {
	Scope            scopeDoc             `json:"scope"`
	ResourcePatterns []resourcePatternDoc `json:"resourcePatterns"`
}

type scopeDoc struct {
	Clusters map[string]string `json:"clusters"`
}

type resourcePatternDoc struct {
	ResourceType string `json:"resourceType"`
	Name         string `json:"name"`
	PatternType  string `json:"patternType"`
}

// escapePathSegment is url.PathEscape with an extra pass that
// percent-encodes the four characters bash interprets inside double
// quotes — '$', '`', '"', '\\'. PathEscape itself is RFC-3986
// compliant and leaves those alone (they're legal in a path segment),
// but our segments end up inside `"${MDS_URL}/.../principals/<seg>/..."`
// so we need stricter escaping than the RFC requires. The result is
// still a valid URL because percent-encoding any byte in a path
// segment is always permitted.
func escapePathSegment(s string) string {
	escaped := url.PathEscape(s)
	// One pass replace; order doesn't matter because each replacement
	// outputs % which is itself already percent-encoded by PathEscape
	// when it appears in the original input.
	replacer := strings.NewReplacer(
		"$", "%24",
		"`", "%60",
		`"`, "%22",
		`\`, "%5C",
	)
	return replacer.Replace(escaped)
}

func buildBody(b types.Binding) bodyDoc {
	clusters := map[string]string{}
	if b.Scope.KafkaCluster != "" {
		clusters["kafka-cluster"] = b.Scope.KafkaCluster
	}
	if b.Scope.SchemaRegistryCluster != "" {
		clusters["schema-registry-cluster"] = b.Scope.SchemaRegistryCluster
	}
	if b.Scope.KSQLCluster != "" {
		clusters["ksql-cluster"] = b.Scope.KSQLCluster
	}
	if b.Scope.ConnectCluster != "" {
		clusters["connect-cluster"] = b.Scope.ConnectCluster
	}
	patterns := make([]resourcePatternDoc, 0, len(b.ResourcePatterns))
	for _, p := range b.ResourcePatterns {
		patterns = append(patterns, resourcePatternDoc{
			ResourceType: string(p.ResourceType),
			Name:         p.Name,
			PatternType:  string(p.PatternType),
		})
	}
	return bodyDoc{
		Scope:            scopeDoc{Clusters: clusters},
		ResourcePatterns: patterns,
	}
}
