// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 Monedula contributors

// Package script renders a Plan as a runnable shell script of
// `confluent iam rbac role-binding create` commands.
package script

import (
	"fmt"
	"io"
	"strings"

	"github.com/monedula-dev/monedula-acl-rbac-converter/pkg/aclrbac/emit"
	"github.com/monedula-dev/monedula-acl-rbac-converter/pkg/aclrbac/emit/shell"
	"github.com/monedula-dev/monedula-acl-rbac-converter/pkg/aclrbac/types"
)

// Options tunes the emitter. PlanPath is woven into the header for audit.
type Options struct {
	PlanPath string
}

// Emitter renders the script.
type Emitter struct {
	opts Options
}

// New returns an Emitter.
func New(opts Options) *Emitter { return &Emitter{opts: opts} }

// Name returns "script".
func (e *Emitter) Name() string { return "script" }

// Emit writes the script. Returns the number of CREATE bindings written.
func (e *Emitter) Emit(w io.Writer, plan types.Plan) (int, error) {
	created := 0
	skipped := 0
	for _, b := range plan.Bindings {
		if b.Action == types.ActionCreate {
			created++
		}
		if b.Action == types.ActionSkipExists {
			skipped++
		}
	}

	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("set -euo pipefail\n\n")
	b.WriteString("# Generated by monedula-acl-rbac emit --format script\n")
	if e.opts.PlanPath != "" {
		b.WriteString("# Plan: " + e.opts.PlanPath + "\n")
	}
	fmt.Fprintf(&b, "# Bindings: %d to create, %d to skip (already exist).\n\n", created, skipped)

	for _, bd := range emit.OrderedBindings(plan.Bindings) {
		if bd.Action == types.ActionSkipExists {
			fmt.Fprintf(&b, "# SKIP (already exists in MDS): %s for %s on %s\n",
				emit.SanitizeComment(bd.Role), emit.SanitizeComment(bd.Principal),
				emit.SanitizeComment(formatPatterns(bd.ResourcePatterns)))
			continue
		}
		b.WriteString("confluent iam rbac role-binding create \\\n")
		fmt.Fprintf(&b, "  --principal %s \\\n", shell.Quote(bd.Principal))
		fmt.Fprintf(&b, "  --role %s \\\n", shell.Quote(bd.Role))
		writeScope(&b, bd.Scope)
		fmt.Fprintf(&b, "  --resource %s", shell.Quote(formatPatterns(bd.ResourcePatterns)))
		if hasPrefixedPattern(bd.ResourcePatterns) {
			b.WriteString(" --prefix")
		}
		fmt.Fprintf(&b, "  # binding %s (source_acl_ids=%v)\n", emit.SanitizeComment(bd.ID), bd.SourceACLIDs)
	}

	_, err := io.WriteString(w, b.String())
	return created, err
}

func writeScope(b *strings.Builder, s types.Scope) {
	if s.KafkaCluster != "" {
		fmt.Fprintf(b, "  --kafka-cluster %s \\\n", shell.Quote(s.KafkaCluster))
	}
	if s.SchemaRegistryCluster != "" {
		fmt.Fprintf(b, "  --schema-registry-cluster %s \\\n", shell.Quote(s.SchemaRegistryCluster))
	}
	if s.KSQLCluster != "" {
		fmt.Fprintf(b, "  --ksql-cluster %s \\\n", shell.Quote(s.KSQLCluster))
	}
	if s.ConnectCluster != "" {
		fmt.Fprintf(b, "  --connect-cluster %s \\\n", shell.Quote(s.ConnectCluster))
	}
	if s.Environment != "" {
		// `confluent iam rbac role-binding create` takes the environment id via
		// the value flag --environment; --current-environment is a boolean.
		fmt.Fprintf(b, "  --environment %s \\\n", shell.Quote(s.Environment))
	}
	// Organization scope has no per-command flag — it comes from the CLI
	// context/login — so there is no valid flag to emit here (the previous
	// --current-organization does not exist). It is surfaced as a header note
	// instead; see Emit.
}

func formatPatterns(p []types.ResourcePattern) string {
	parts := make([]string, 0, len(p))
	for _, rp := range p {
		// PREFIXED patterns are expressed via the CLI's --prefix flag (see
		// hasPrefixedPattern), NOT a trailing '*' — the CLI would read a '*'
		// as a literal topic name.
		parts = append(parts, string(rp.ResourceType)+":"+rp.Name)
	}
	return strings.Join(parts, ",")
}

// hasPrefixedPattern reports whether any pattern is PREFIXED, in which case the
// command needs the boolean --prefix flag. The planner emits one pattern per
// binding, so this is unambiguous in practice.
func hasPrefixedPattern(p []types.ResourcePattern) bool {
	for _, rp := range p {
		if rp.PatternType == types.PatternPrefixed {
			return true
		}
	}
	return false
}
